package it.polimi.se2018.model;

public enum ACTION_TYPE {
    ASK_PICK_DIE,
    ASK_PLACE_DIE,
    ASK_INCREASE_DECREASE,
    ASK_DIE_VALUE,
    ASK_ANOTHER_ACTION,
    DO_PLACE_DIE,
    DO_INCREASE_DECREASE,
    DO_SWAP,
    DO_SHUFFLE,
    DO_SHUFFLE_ALL,
    DO_FLIP,
    DO_SAVE_COLOR,
    CHECK_EXISTS_COLOR_RT,
    CHECK_SAME_COLOR,
    CHECK_POSSIBLE_PLACEMENT,
    CHECK_ANOTHER_ACTION
}
